// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crud_operation._SysDbContext;

namespace crud_operation.Migrations
{
    [DbContext(typeof(_sysdbcontext))]
    [Migration("20240219040048_Initial-Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("crud_operation.Models.RmpiStuInfoModel", b =>
                {
                    b.Property<int>("StuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StuDept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StuEmail")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StuPhoto")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StuReg")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StuRoll")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StuID");

                    b.ToTable("TblRmpiStuInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
